export type GlossaryLocale = 'de' | 'en'

export type GlossaryEntry = {
  id: string
  de: { term: string; definition: string }
  en: { term: string; definition: string }
}

type RawEntry = readonly [
  id: string,
  deTerm: string,
  deDefinition: string,
  enTerm: string,
  enDefinition: string,
]

const RAW_ENTRIES = [
  [
    'abgeschlossenheitsbescheinigung',
    'Abgeschlossenheitsbescheinigung',
    'Bescheinigung der Baubehörde, dass eine Einheit baulich von anderen Einheiten getrennt ist. Sie wird benötigt, um Wohnungseigentum im Grundbuch anzulegen.',
    'Certificate of self-containment',
    'Confirmation from the building authority that a unit is structurally separate from other units. It is needed when creating individual apartment ownership in the land register.',
  ],
  [
    'annuitaet',
    'Annuität',
    'Gleichbleibende Rate eines Annuitätendarlehens aus Zins und Tilgung. Während der Zinsanteil sinkt, steigt der Tilgungsanteil.',
    'Annuity payment',
    'The regular payment on an amortising loan, made up of interest and principal. As the interest share falls, the principal repayment share rises.',
  ],
  [
    'auflassung',
    'Auflassung',
    'Notariell erklärte Einigung von Käufer und Verkäufer über den Eigentumsübergang. Sie bildet die Grundlage für die spätere Umschreibung im Grundbuch.',
    'Conveyance agreement',
    'The notarised agreement between buyer and seller that ownership is to transfer. It is the basis for the later change in the land register.',
  ],
  [
    'auflassungsvormerkung',
    'Auflassungsvormerkung',
    'Eintrag im Grundbuch, der den Anspruch des Käufers auf Eigentumsübertragung sichert. Er schützt den vereinbarten Erwerb bis zur endgültigen Umschreibung.',
    'Priority notice',
    'An entry in the land register securing the buyer’s claim to ownership. It protects the agreed purchase until the final transfer is registered.',
  ],
  [
    'baulast',
    'Baulast',
    'Öffentlich-rechtliche Verpflichtung eines Grundstückseigentümers gegenüber der Baubehörde, etwa zur Duldung einer Zufahrt. Sie steht im Baulastenverzeichnis und sollte vor dem Kauf geprüft werden.',
    'Public-law building obligation',
    'A public-law obligation attached to land, such as allowing access for another plot. It is recorded in the local building-obligations register and should be checked before purchase.',
  ],
  [
    'bautraeger',
    'Bauträger',
    'Unternehmen, das ein Bauvorhaben auf eigenem oder erworbenem Grundstück entwickelt und Einheiten an Käufer veräußert. Verträge verbinden häufig Grundstückskauf und Bauleistung.',
    'Property developer',
    'A company that develops a project on land it owns or acquires and sells the completed units. Contracts often combine the land purchase with construction obligations.',
  ],
  [
    'beleihungswert',
    'Beleihungswert',
    'Vorsichtig ermittelter Wert, den ein Kreditinstitut bei der Besicherung einer Finanzierung ansetzt. Er kann vom aktuellen Marktwert abweichen.',
    'Mortgage lending value',
    'A prudently assessed value used by a lender when securing a property loan. It may differ from the current market value.',
  ],
  [
    'bereitstellungszins',
    'Bereitstellungszins',
    'Entgelt für einen zugesagten, aber noch nicht abgerufenen Darlehensteil. Es kann vor allem bei schrittweise ausgezahlten Baufinanzierungen relevant werden.',
    'Commitment interest',
    'A charge on an approved but not yet drawn portion of a loan. It can be relevant where construction finance is paid out in stages.',
  ],
  [
    'bodenrichtwert',
    'Bodenrichtwert',
    'Vom Gutachterausschuss ermittelter durchschnittlicher Lagewert für Grund und Boden. Er ist eine Orientierung und kein individueller Verkaufspreis.',
    'Standard land value',
    'An average location-based land value determined by the local valuation committee. It is a reference point, not an individual sale price.',
  ],
  [
    'courtage',
    'Courtage',
    'Anderes Wort für Maklerprovision. Sie wird bei erfolgreicher Vermittlung entsprechend der getroffenen Vereinbarung und den gesetzlichen Vorgaben fällig.',
    'Estate agent’s commission',
    'Another term for an estate agent’s fee. It becomes payable after a successful transaction in line with the agreement and applicable law.',
  ],
  [
    'denkmalschutz',
    'Denkmalschutz',
    'Schutzstatus für kulturhistorisch bedeutsame Gebäude. Veränderungen können genehmigungspflichtig sein; zugleich können besondere Förder- oder Steuerregeln gelten.',
    'Listed-building protection',
    'Protected status for buildings of cultural or historical importance. Alterations may need approval, while special grant or tax rules can sometimes apply.',
  ],
  [
    'dienstbarkeit',
    'Dienstbarkeit',
    'Im Grundbuch gesichertes Recht, ein fremdes Grundstück in bestimmter Weise zu nutzen, etwa als Wege-, Leitungs- oder Wohnrecht.',
    'Easement',
    'A right recorded in the land register allowing specified use of another person’s land, such as access, utilities, or residence.',
  ],
  [
    'disagio',
    'Disagio',
    'Abschlag vom Darlehensbetrag, der bei Auszahlung einbehalten wird. Er wirkt wirtschaftlich wie vorausbezahlter Zins und gehört in den Gesamtkostenvergleich.',
    'Disagio',
    'A deduction retained when a loan is paid out. Economically it acts like prepaid interest and should be included when comparing total borrowing costs.',
  ],
  [
    'effektiver-jahreszins',
    'Effektiver Jahreszins',
    'Jährlicher Prozentsatz, der den Sollzins und bestimmte weitere Kreditkosten zusammenfasst. Er erleichtert den Vergleich ähnlich strukturierter Finanzierungsangebote.',
    'Annual percentage rate',
    'An annual rate combining the borrowing rate with certain additional credit costs. It helps compare financing offers with a similar structure.',
  ],
  [
    'eigenkapital',
    'Eigenkapital',
    'Eigene Mittel, die ein Käufer in den Erwerb einbringt. Höhe und Herkunft beeinflussen Finanzierungsspielraum und Kreditkonditionen.',
    'Equity',
    'The buyer’s own funds contributed to a purchase. Their amount and source affect financing capacity and loan terms.',
  ],
  [
    'energieausweis',
    'Energieausweis',
    'Dokument mit Kennwerten zur energetischen Qualität eines Gebäudes. Welche Art benötigt wird und wann sie vorzulegen ist, hängt vom Gebäude und den gesetzlichen Vorgaben ab.',
    'Energy performance certificate',
    'A document summarising a building’s energy performance. The required type and timing depend on the building and applicable regulations.',
  ],
  [
    'erbbaurecht',
    'Erbbaurecht',
    'Zeitlich begrenztes Recht, auf einem fremden Grundstück ein Gebäude zu besitzen oder zu errichten. Dafür wird üblicherweise ein Erbbauzins vereinbart.',
    'Heritable building right',
    'A time-limited right to own or build a property on land belonging to someone else. A recurring ground rent is usually payable.',
  ],
  [
    'erbengemeinschaft',
    'Erbengemeinschaft',
    'Mehrere Erben verwalten den Nachlass gemeinsam. Entscheidungen über eine geerbte Immobilie erfordern deshalb abgestimmtes Vorgehen und klare Vollmachten.',
    'Community of heirs',
    'Several heirs administer an estate jointly. Decisions about inherited property therefore require coordination and clear authority.',
  ],
  [
    'erschliessungskosten',
    'Erschließungskosten',
    'Kosten für die Anbindung eines Grundstücks an öffentliche Infrastruktur wie Straße, Wasser oder Kanal. Offene Beiträge sollten vor Kauf oder Verkauf geklärt werden.',
    'Site development costs',
    'Costs of connecting land to public infrastructure such as roads, water, or drainage. Outstanding charges should be clarified before purchase or sale.',
  ],
  [
    'ertragswertverfahren',
    'Ertragswertverfahren',
    'Bewertungsverfahren, bei dem nachhaltig erzielbare Erträge und der Grundstückswert im Mittelpunkt stehen. Es wird häufig bei vermieteten Objekten eingesetzt.',
    'Income approach',
    'A valuation method focused on sustainable income and the land value. It is commonly used for rented and investment properties.',
  ],
  [
    'expose',
    'Exposé',
    'Strukturierte Verkaufsunterlage mit Bildern, Grundrissen, Objektangaben und Beschreibung. Inhalte sollten vollständig, verständlich und überprüfbar sein.',
    'Property brochure',
    'A structured sales document containing photographs, floor plans, property details, and description. Its content should be complete, clear, and verifiable.',
  ],
  [
    'faktor',
    'Faktor',
    'Verhältnis von Kaufpreis zu Jahresnettokaltmiete. Der Wert dient als schnelle Vergleichsgröße, ersetzt aber keine vollständige Prüfung von Kosten, Zustand und Ertrag.',
    'Purchase price multiple',
    'The ratio of purchase price to annual net rent. It is a quick comparison measure but does not replace a full review of costs, condition, and income.',
  ],
  [
    'finanzierungsbestaetigung',
    'Finanzierungsbestätigung',
    'Schriftliche Einschätzung eines Kreditinstituts oder Finanzierungsvermittlers, dass eine Finanzierung grundsätzlich darstellbar erscheint. Umfang und Verbindlichkeit können variieren.',
    'Proof of finance',
    'Written confirmation from a lender or finance broker that funding appears feasible in principle. Its scope and degree of commitment can vary.',
  ],
  [
    'flurkarte',
    'Flurkarte',
    'Amtliche Kartendarstellung von Flurstücken, Grundstücksgrenzen und Lagebezeichnungen. Sie gehört zu den wichtigen Unterlagen bei Prüfung und Finanzierung.',
    'Cadastral map',
    'An official map showing parcels, boundaries, and location identifiers. It is an important document for due diligence and financing.',
  ],
  [
    'gemarkung',
    'Gemarkung',
    'Bezirk des Liegenschaftskatasters, der mehrere Flurstücke umfasst. Zusammen mit Flur und Flurstück hilft er, ein Grundstück eindeutig zu bezeichnen.',
    'Cadastral district',
    'An area in the cadastral register containing multiple parcels. Together with the parcel references, it identifies a property precisely.',
  ],
  [
    'geg',
    'GEG',
    'Gebäudeenergiegesetz. Es bündelt Regeln zur energetischen Qualität von Gebäuden und zur eingesetzten Anlagentechnik. Für den Einzelfall zählt die jeweils geltende Fassung.',
    'Building Energy Act (GEG)',
    'Germany’s Building Energy Act combines rules on building energy performance and technical systems. The version in force at the relevant time applies.',
  ],
  [
    'geschossflaechenzahl',
    'Geschossflächenzahl',
    'Die Geschossflächenzahl (GFZ) beschreibt das Verhältnis der zulässigen Geschossfläche zur Grundstücksfläche. Maßgeblich sind Bebauungsplan und Baurecht.',
    'Floor-area ratio',
    'The floor-area ratio describes permitted gross floor area relative to the plot size. The development plan and local planning law determine what is allowed.',
  ],
  [
    'grundbuch',
    'Grundbuch',
    'Amtliches Register mit Angaben zu Eigentum, Grundpfandrechten und weiteren Rechten an Grundstücken. Einsicht ist nur unter den gesetzlichen Voraussetzungen möglich.',
    'Land register',
    'The official register recording ownership, mortgages, and other rights over land. Access is available only under the legal conditions.',
  ],
  [
    'grunderwerbsteuer',
    'Grunderwerbsteuer',
    'Steuer, die beim Erwerb eines Grundstücks oder einer Immobilie anfällt. Der Satz und mögliche Ausnahmen richten sich nach Standort und Einzelfall.',
    'Property transfer tax',
    'A tax charged when land or property is acquired. The rate and possible exemptions depend on the location and circumstances.',
  ],
  [
    'grundflaechenzahl',
    'Grundflächenzahl',
    'Die Grundflächenzahl (GRZ) gibt an, welcher Anteil eines Grundstücks grundsätzlich überbaut werden darf. Weitere Regeln des Bebauungsplans bleiben zu beachten.',
    'Site occupancy ratio',
    'The site occupancy ratio indicates what share of a plot may generally be built on. Other requirements in the development plan still apply.',
  ],
  [
    'grundschuld',
    'Grundschuld',
    'Grundpfandrecht, das häufig zur Sicherung eines Immobiliendarlehens dient. Nach Rückzahlung des Kredits wird es nicht automatisch aus dem Grundbuch entfernt.',
    'Land charge',
    'A security right over property commonly used for mortgage lending. It is not automatically removed from the land register when the loan is repaid.',
  ],
  [
    'grundsteuer',
    'Grundsteuer',
    'Kommunale Steuer auf Grundbesitz. Ihre Höhe wird aus den gesetzlichen Bewertungsgrundlagen und dem Hebesatz der jeweiligen Gemeinde berechnet.',
    'Property tax',
    'A municipal tax on property ownership. It is calculated using the statutory assessment basis and the multiplier set by the municipality.',
  ],
  [
    'hausgeld',
    'Hausgeld',
    'Regelmäßige Zahlung von Wohnungseigentümern für gemeinschaftliche Kosten, Verwaltung und Rücklagen. Abrechnung und Wirtschaftsplan zeigen die Zusammensetzung.',
    'Service charge for owners',
    'The regular payment by apartment owners towards shared costs, management, and reserves. The annual statement and budget show how it is composed.',
  ],
  [
    'hypothek',
    'Hypothek',
    'Grundpfandrecht, das unmittelbar an eine bestimmte Forderung gebunden ist. In der Finanzierungspraxis wird häufig stattdessen die flexiblere Grundschuld genutzt.',
    'Mortgage (Hypothek)',
    'A security right over land directly tied to a specific debt. In German lending practice, the more flexible land charge is often used instead.',
  ],
  [
    'instandhaltungsruecklage',
    'Instandhaltungsrücklage',
    'Von einer Wohnungseigentümergemeinschaft angesparte Mittel für künftige Erhaltungsmaßnahmen am Gemeinschaftseigentum.',
    'Maintenance reserve',
    'Funds accumulated by an owners’ association for future maintenance and repair of jointly owned parts of the building.',
  ],
  [
    'jahresrohertrag',
    'Jahresrohertrag',
    'Summe der nachhaltig erzielbaren jährlichen Einnahmen vor Abzug der Bewirtschaftungskosten. Sie ist eine Größe in der Ertragswertermittlung.',
    'Gross annual income',
    'The sustainable annual property income before operating costs are deducted. It is one input in income-based valuation.',
  ],
  [
    'kaufnebenkosten',
    'Kaufnebenkosten',
    'Zusätzliche Erwerbskosten neben dem Kaufpreis, insbesondere Steuern, Notar- und Grundbuchkosten sowie gegebenenfalls Maklerprovision. Die konkrete Höhe hängt vom Fall ab.',
    'Ancillary purchase costs',
    'Costs in addition to the purchase price, especially tax, notary and land-register fees, and possibly agent’s commission. The amount depends on the transaction.',
  ],
  [
    'kaufpreisfaelligkeit',
    'Kaufpreisfälligkeit',
    'Zeitpunkt, zu dem der Kaufpreis nach den Bedingungen des notariellen Vertrags zu zahlen ist. Der Notar informiert die Beteiligten, wenn die vereinbarten Voraussetzungen vorliegen.',
    'Purchase price due date',
    'The point when the purchase price must be paid under the notarised contract. The notary informs the parties once the agreed conditions have been met.',
  ],
  [
    'kubatur',
    'Kubatur',
    'Rauminhalt eines Gebäudes in Kubikmetern. Er kann bei Planung, Bewertung und Versicherung als zusätzliche Größenangabe dienen.',
    'Building volume',
    'The enclosed volume of a building measured in cubic metres. It can be relevant to planning, valuation, and insurance.',
  ],
  [
    'lastenfreistellung',
    'Lastenfreistellung',
    'Ablösung oder Löschung nicht zu übernehmender Grundbuchbelastungen im Zuge des Verkaufs. Der notarielle Vertrag regelt das Verfahren.',
    'Release of encumbrances',
    'The settlement or deletion of land-register charges that the buyer is not taking over. The notarised contract sets out the process.',
  ],
  [
    'loeschungsbewilligung',
    'Löschungsbewilligung',
    'Erklärung des Berechtigten, häufig einer Bank, dass ein eingetragenes Recht im Grundbuch gelöscht werden darf.',
    'Consent to cancellation',
    'A declaration by the right-holder, often a bank, allowing a registered right to be removed from the land register.',
  ],
  [
    'makleralleinauftrag',
    'Makleralleinauftrag',
    'Vereinbarung, mit der ein Eigentümer für einen bestimmten Zeitraum einen Makler exklusiv mit der Vermarktung beauftragt. Leistungsumfang und Pflichten sollten klar geregelt sein.',
    'Sole agency agreement',
    'An agreement appointing one estate agent exclusively for a defined period. Services, responsibilities, and obligations should be stated clearly.',
  ],
  [
    'maklerprovision',
    'Maklerprovision',
    'Vergütung für eine erfolgreiche Maklerleistung. Wer sie in welcher Höhe trägt, richtet sich nach Objektart, Vereinbarung und den gesetzlichen Vorgaben.',
    'Estate agent’s fee',
    'Payment for a successful estate agency service. Who pays and how much depends on the property, the agreement, and applicable law.',
  ],
  [
    'marktwert',
    'Marktwert',
    'Geschätzter Preis, der unter gewöhnlichen Marktbedingungen zu einem bestimmten Stichtag erreichbar erscheint. Er ist nicht mit Wunsch-, Beleihungs- oder Versicherungswert gleichzusetzen.',
    'Market value',
    'The estimated price achievable under normal market conditions at a specified date. It is distinct from an asking price, lending value, or insurance value.',
  ],
  [
    'niessbrauch',
    'Nießbrauch',
    'Umfassendes Recht, eine Sache zu nutzen und Erträge daraus zu ziehen, ohne Eigentümer zu sein. Bei Immobilien wird es regelmäßig im Grundbuch gesichert.',
    'Usufruct',
    'A broad right to use an asset and receive its income without owning it. For property, the right is normally recorded in the land register.',
  ],
  [
    'notaranderkonto',
    'Notaranderkonto',
    'Treuhandkonto eines Notars für die Abwicklung eines Kaufpreises. Es wird nur eingesetzt, wenn ein berechtigtes Sicherungsinteresse besteht.',
    'Notary escrow account',
    'An escrow account operated by a notary for handling purchase funds. It is used only where a justified security interest exists.',
  ],
  [
    'notartermin',
    'Notartermin',
    'Termin zur Beurkundung des Immobilienkaufvertrags. Der Notar erläutert den Vertrag neutral und dokumentiert die Erklärungen der Beteiligten.',
    'Notary appointment',
    'The appointment at which the property purchase agreement is notarised. The notary explains the contract impartially and records the parties’ declarations.',
  ],
  [
    'nutzflaeche',
    'Nutzfläche',
    'Fläche, die bestimmten Nutzungen dient, aber nicht zwingend als Wohnfläche zählt, etwa Lager-, Technik- oder Gewerbeflächen. Maßgeblich ist die verwendete Berechnungsgrundlage.',
    'Usable floor area',
    'Space serving particular uses but not necessarily counted as living area, such as storage, plant, or commercial space. The stated calculation method matters.',
  ],
  [
    'objektunterlagen',
    'Objektunterlagen',
    'Dokumente zur rechtlichen, technischen und wirtschaftlichen Prüfung einer Immobilie, etwa Grundbuchauszug, Pläne, Energieausweis und bei Wohnungen WEG-Unterlagen.',
    'Property documents',
    'Documents used for legal, technical, and financial due diligence, such as the land-register extract, plans, energy certificate, and owners’ association papers.',
  ],
  [
    'pacht',
    'Pacht',
    'Zeitweise Überlassung einer Sache oder eines Betriebs gegen Entgelt. Anders als bei der Miete kann die Vereinbarung auch das Recht umfassen, Erträge zu erwirtschaften.',
    'Lease with usufruct rights',
    'Temporary use of an asset or business in return for payment. Unlike a standard tenancy, it can include the right to generate income from the asset.',
  ],
  [
    'provisionsteilung',
    'Provisionsteilung',
    'Aufteilung einer Maklerprovision zwischen den Parteien. Für bestimmte Wohnimmobiliengeschäfte mit Verbrauchern gelten besondere gesetzliche Regeln.',
    'Commission sharing',
    'The division of an estate agent’s fee between the parties. Special statutory rules apply to certain residential transactions involving consumers.',
  ],
  [
    'realteilung',
    'Realteilung',
    'Vermessungs- und grundbuchrechtliche Aufteilung eines Grundstücks in selbstständige Flurstücke. Planungsrecht und Erschließung müssen dabei geprüft werden.',
    'Subdivision of land',
    'The surveying and legal division of a plot into independent parcels. Planning rules and access to infrastructure must be checked.',
  ],
  [
    'rendite',
    'Rendite',
    'Verhältnis von Ertrag zu eingesetztem Kapital. Welche Renditekennzahl sinnvoll ist, hängt davon ab, welche Kosten und Zeiträume berücksichtigt werden.',
    'Yield',
    'The relationship between income and invested capital. The useful measure depends on which costs and time period are included.',
  ],
  [
    'reservierungsvereinbarung',
    'Reservierungsvereinbarung',
    'Vereinbarung, eine Immobilie vorübergehend nicht anderweitig anzubieten. Inhalt, Dauer, Entgelt und rechtliche Bindung sollten sorgfältig geprüft werden.',
    'Reservation agreement',
    'An agreement to withhold a property from other buyers for a limited period. Its terms, duration, fee, and legal effect should be reviewed carefully.',
  ],
  [
    'sanierungsstau',
    'Sanierungsstau',
    'Über längere Zeit aufgeschobene Instandsetzung oder Modernisierung. Für eine Bewertung werden Umfang, Dringlichkeit und Kostenrisiko sachlich eingeordnet.',
    'Deferred maintenance',
    'Repairs or modernisation postponed over a longer period. Valuation should consider their scope, urgency, and cost risk objectively.',
  ],
  [
    'schufa',
    'Schufa',
    'Private Wirtschaftsauskunftei in Deutschland. Ihre Informationen können bei einer Bonitäts- oder Finanzierungsprüfung eine Rolle spielen.',
    'SCHUFA credit bureau',
    'A private German credit bureau. Its information may be considered during creditworthiness and finance checks.',
  ],
  [
    'sondereigentum',
    'Sondereigentum',
    'Bereiche einer Wohnungseigentumsanlage, die einem Eigentümer allein zugeordnet sind. Die Teilungserklärung grenzt sie vom Gemeinschaftseigentum ab.',
    'Individual ownership',
    'Parts of a condominium allocated exclusively to one owner. The declaration of division distinguishes them from jointly owned elements.',
  ],
  [
    'sondernutzungsrecht',
    'Sondernutzungsrecht',
    'Befugnis eines Eigentümers, einen Teil des Gemeinschaftseigentums allein zu nutzen, etwa einen Gartenbereich oder Stellplatz.',
    'Exclusive right of use',
    'An owner’s right to use part of the common property exclusively, such as a garden area or parking space.',
  ],
  [
    'spekulationssteuer',
    'Spekulationssteuer',
    'Umgangssprachliche Bezeichnung für Einkommensteuer auf bestimmte private Veräußerungsgewinne. Ob sie anfällt, hängt unter anderem von Haltedauer und Nutzung ab.',
    'Tax on private disposal gains',
    'An informal term for income tax on certain gains from private disposals. Liability depends, among other things, on ownership period and use.',
  ],
  [
    'teilungserklaerung',
    'Teilungserklärung',
    'Notariell beglaubigte oder beurkundete Erklärung, die ein Gebäude in Wohnungs- oder Teileigentum aufteilt und die Zuordnung von Flächen beschreibt.',
    'Declaration of division',
    'A notarised or officially certified document dividing a building into apartment or commercial units and describing how areas are allocated.',
  ],
  [
    'teilungsversteigerung',
    'Teilungsversteigerung',
    'Gerichtliches Verfahren zur Aufhebung gemeinschaftlichen Eigentums, beispielsweise bei einer Erbengemeinschaft oder Trennung. Vorher sollten einvernehmliche Alternativen geprüft werden.',
    'Partition auction',
    'A court process used to dissolve joint property ownership, for example after inheritance or separation. Agreed alternatives should be explored beforehand.',
  ],
  [
    'tilgung',
    'Tilgung',
    'Teil einer Darlehenszahlung, der die Restschuld reduziert. Höhe und Verlauf bestimmen zusammen mit dem Zins die Laufzeit und Gesamtkosten.',
    'Principal repayment',
    'The part of a loan payment that reduces the outstanding balance. Its amount and progression, together with interest, determine term and total cost.',
  ],
  [
    'uebergabeprotokoll',
    'Übergabeprotokoll',
    'Dokumentation der Immobilienübergabe mit Schlüsseln, Zählerständen, Unterlagen und festgehaltenem Zustand. Beide Seiten sollten eine Ausfertigung erhalten.',
    'Handover record',
    'A record of the property handover covering keys, meter readings, documents, and noted condition. Both parties should retain a copy.',
  ],
  [
    'umschreibung',
    'Umschreibung',
    'Eintragung des Käufers als neuer Eigentümer im Grundbuch. Sie erfolgt nach Erfüllung der vertraglichen und behördlichen Voraussetzungen.',
    'Registration of new ownership',
    'Registration of the buyer as the new owner in the land register after the contractual and administrative conditions have been met.',
  ],
  [
    'valutierung',
    'Valutierung',
    'Tatsächliche Auszahlung eines zugesagten Darlehens. Voraussetzungen und Zeitpunkt richten sich nach Kreditvertrag und Verwendungszweck.',
    'Loan disbursement',
    'The actual payment of an approved loan. Conditions and timing depend on the loan agreement and its purpose.',
  ],
  [
    'verkehrswert',
    'Verkehrswert',
    'Gesetzlich definierter Wertbegriff für den Preis, der zu einem Stichtag im gewöhnlichen Geschäftsverkehr erzielbar wäre. Besondere persönliche Verhältnisse bleiben außer Betracht.',
    'Statutory market value',
    'A legally defined value representing the price achievable in an ordinary transaction at a specified date, excluding unusual personal circumstances.',
  ],
  [
    'vorfaelligkeitsentschaedigung',
    'Vorfälligkeitsentschädigung',
    'Mögliche Entschädigung eines Kreditinstituts bei vorzeitiger Rückzahlung eines fest verzinsten Darlehens. Voraussetzungen und Berechnung sind rechtlich geregelt.',
    'Early repayment charge',
    'A possible lender charge when a fixed-rate loan is repaid early. Eligibility and calculation are governed by law.',
  ],
  [
    'vorkaufsrecht',
    'Vorkaufsrecht',
    'Recht, unter festgelegten Voraussetzungen anstelle eines Dritten in einen Kaufvertrag einzutreten. Es kann vertraglich oder gesetzlich begründet sein.',
    'Right of first refusal',
    'A right, under defined conditions, to take the place of a third-party buyer in a purchase agreement. It may arise by contract or by law.',
  ],
  [
    'weg',
    'WEG',
    'Abkürzung für Wohnungseigentumsgesetz und häufig auch für die Gemeinschaft der Wohnungseigentümer. Der Zusammenhang zeigt, welche Bedeutung gemeint ist.',
    'Condominium law / owners’ association',
    'An abbreviation used for Germany’s Condominium Act and, in everyday usage, for the community of apartment owners. Context determines the meaning.',
  ],
  [
    'wertgutachten',
    'Wertgutachten',
    'Nachvollziehbar begründete Wertermittlung, häufig durch einen qualifizierten Sachverständigen. Zweck und erforderliche Tiefe bestimmen Form und Verfahren.',
    'Formal valuation report',
    'A reasoned assessment of value, often prepared by a qualified valuer. Its purpose determines the required form, depth, and method.',
  ],
  [
    'wohnflaechenverordnung',
    'Wohnflächenverordnung',
    'Regelwerk für die Berechnung von Wohnfläche in bestimmten Anwendungsbereichen. Dachschrägen, Balkone und weitere Flächen werden nach festgelegten Kriterien berücksichtigt.',
    'Living Space Ordinance',
    'German rules for calculating living area in specified contexts. Sloping ceilings, balconies, and other areas are treated according to defined criteria.',
  ],
  [
    'wohnrecht',
    'Wohnrecht',
    'Recht, eine Immobilie oder einen Teil davon zu bewohnen. Wird es im Grundbuch gesichert, bindet es grundsätzlich auch spätere Eigentümer.',
    'Right of residence',
    'A right to occupy a property or part of it. If registered in the land register, it generally remains binding on later owners.',
  ],
  [
    'wohnungsgeberbescheinigung',
    'Wohnungsgeberbescheinigung',
    'Bestätigung des Wohnungsgebers über den Einzug eines Bewohners zur Vorlage bei der Meldebehörde. Inhalt und Fristen richten sich nach dem Melderecht.',
    'Landlord confirmation of occupancy',
    'A landlord’s confirmation that a resident has moved in, used for local registration. Required content and deadlines follow registration law.',
  ],
  [
    'zinsbindung',
    'Zinsbindung',
    'Zeitraum, in dem der vereinbarte Sollzins eines Darlehens unverändert bleibt. Danach wird für eine Restschuld gegebenenfalls eine Anschlussfinanzierung benötigt.',
    'Fixed-interest period',
    'The period during which a loan’s agreed borrowing rate remains unchanged. Any remaining balance may need refinancing afterwards.',
  ],
  [
    'zustandsnote',
    'Zustandsnote',
    'Zusammenfassende Einordnung des baulichen und technischen Objektzustands. Sie sollte auf dokumentierten Merkmalen statt auf einem pauschalen Eindruck beruhen.',
    'Condition rating',
    'A summary assessment of a property’s structural and technical condition. It should be based on documented characteristics rather than a general impression.',
  ],
  [
    'zwangsversteigerung',
    'Zwangsversteigerung',
    'Gerichtliche Verwertung einer Immobilie, häufig zur Befriedigung von Gläubigern. Ablauf, Risiken und Gebotsbedingungen unterscheiden sich deutlich von einem freien Verkauf.',
    'Foreclosure auction',
    'A court-administered sale of property, often used to satisfy creditors. Its process, risks, and bidding conditions differ substantially from an open-market sale.',
  ],
  [
    'zweckerklaerung',
    'Zweckerklärung',
    'Vereinbarung darüber, welche Forderungen eine Grundschuld absichert. Sie verbindet das abstrakte Grundpfandrecht mit dem konkreten Sicherungszweck.',
    'Security purpose agreement',
    'An agreement defining which debts a land charge secures. It links the abstract security right to its specific purpose.',
  ],
] as const satisfies readonly RawEntry[]

export const GLOSSARY_ENTRIES: readonly GlossaryEntry[] = RAW_ENTRIES.map(
  ([id, deTerm, deDefinition, enTerm, enDefinition]) => ({
    id,
    de: { term: deTerm, definition: deDefinition },
    en: { term: enTerm, definition: enDefinition },
  }),
)
