import type { BuyerProfileRecord } from '../buyer-profiles'
import { d, t } from './shared'

/** Suchprofile für Nürnberg — zusammen decken sie alle 60 Nürnberger Stadtteilseiten ab. */
export const NUERNBERG_PROFILES: readonly BuyerProfileRecord[] = [
  {
    id: 'nue-01',
    city: 'nuernberg',
    districts: [d('laufamholz', 'Laufamholz'), d('fischbach', 'Fischbach'), d('brunn', 'Brunn')],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 870_000,
    roomsMin: 5,
    areaMin: 130,
    financing: 'checked',
    headline: t(
      'Familie sucht Einfamilienhaus im Nürnberger Osten',
      'Family looking for a detached house in eastern Nuremberg',
    ),
    brief: t(
      'Zwei Kinder, beide Eltern berufstätig. Gesucht ist ein freistehendes Haus mit Garten – gern auch älteres Baujahr mit Modernisierungsbedarf.',
      'Two children, both parents working. They want a detached house with a garden and are open to an older build that needs modernising.',
    ),
    wishes: [
      t('Garten', 'Garden'),
      t('Grundschule fußläufig', 'Primary school within walking distance'),
      t('Einzug bis Sommer 2027', 'Move-in by summer 2027'),
    ],
  },
  {
    id: 'nue-02',
    city: 'nuernberg',
    districts: [
      d('langwasser', 'Langwasser'),
      d('gibitzenhof', 'Gibitzenhof'),
      d('hohe-marter', 'Hohe Marter'),
    ],
    segment: 'single',
    propertyType: 'apartment',
    budgetMax: 120_000,
    roomsMin: 1,
    areaMin: 25,
    financing: 'checked',
    headline: t('Single sucht Apartment zur Eigennutzung', 'Single buyer looking for a studio'),
    brief: t(
      'Erstes Eigentum statt Miete. Ein kompaktes Apartment mit guter U-Bahn-Anbindung genügt – Hauptsache bezugsfertig.',
      'A first home instead of renting. A compact studio with good underground links is enough – as long as it is ready to move into.',
    ),
    wishes: [
      t('U-Bahn in Laufweite', 'Underground within walking distance'),
      t('Balkon wünschenswert', 'Balcony preferred'),
      t('bezugsfrei', 'Vacant on completion'),
    ],
  },
  {
    id: 'nue-03',
    city: 'nuernberg',
    districts: [
      d('gostenhof', 'Gostenhof'),
      d('galgenhof', 'Galgenhof'),
      d('suedstadt', 'Südstadt'),
    ],
    segment: 'investor',
    propertyType: 'multi-family',
    budgetMax: 2_000_000,
    financing: 'equity',
    headline: t(
      'Investor sucht Mehrfamilienhaus als Kapitalanlage',
      'Investor looking for an apartment building',
    ),
    brief: t(
      'Langfristiger Bestandshalter aus der Region. Vermietete Objekte sind ausdrücklich erwünscht, auch mit Instandhaltungsstau.',
      'A long-term holder from the region. Tenanted buildings are explicitly welcome, including those with deferred maintenance.',
    ),
    wishes: [
      t('ab 6 Wohneinheiten', '6 or more units'),
      t('vermietet', 'Tenanted'),
      t('diskrete Abwicklung', 'Discreet transaction'),
    ],
  },
  {
    id: 'nue-04',
    city: 'nuernberg',
    districts: [d('st-johannis', 'St. Johannis'), d('maxfeld', 'Maxfeld'), d('woehrd', 'Wöhrd')],
    segment: 'couple',
    propertyType: 'apartment',
    budgetMax: 480_000,
    roomsMin: 3,
    areaMin: 80,
    financing: 'checked',
    headline: t(
      'Paar sucht Altbauwohnung mit Balkon',
      'Couple looking for a period apartment with a balcony',
    ),
    brief: t(
      'Beide arbeiten in der Innenstadt und wollen kurze Wege. Altbau mit hohen Decken bevorzugt, ein jüngeres Baujahr kommt ebenfalls infrage.',
      'Both work in the city centre and want short commutes. A period building with high ceilings is preferred; a newer build is also possible.',
    ),
    wishes: [
      t('Balkon oder Loggia', 'Balcony or loggia'),
      t('Altbau bevorzugt', 'Period building preferred'),
      t('Innenstadt mit dem Rad erreichbar', 'City centre by bike'),
    ],
  },
  {
    id: 'nue-05',
    city: 'nuernberg',
    districts: [d('moegeldorf', 'Mögeldorf'), d('zabo', 'Zabo'), d('st-jobst', 'St. Jobst')],
    segment: 'retirees',
    propertyType: 'apartment',
    budgetMax: 420_000,
    roomsMin: 2,
    areaMin: 70,
    financing: 'cash',
    headline: t(
      'Paar im Ruhestand sucht barrierearme Wohnung',
      'Retired couple looking for a step-free apartment',
    ),
    brief: t(
      'Das eigene Haus ist zu groß geworden. Gesucht ist eine gut geschnittene Wohnung mit Aufzug, gern im vertrauten Stadtteil.',
      'Their house has become too big. They want a well-planned apartment with a lift, ideally in a familiar neighbourhood.',
    ),
    wishes: [
      t('Aufzug', 'Lift'),
      t('Einkauf und Arzt zu Fuß', 'Shops and doctors on foot'),
      t('Tiefgaragenstellplatz', 'Underground parking space'),
    ],
  },
  {
    id: 'nue-06',
    city: 'nuernberg',
    districts: [
      d('eibach', 'Eibach'),
      d('katzwang', 'Katzwang'),
      d('reichelsdorf', 'Reichelsdorf'),
    ],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 550_000,
    roomsMin: 4,
    areaMin: 110,
    financing: 'checked',
    headline: t(
      'Handwerkerfamilie sucht Haus mit Sanierungsbedarf',
      'Tradesperson’s family looking for a house to renovate',
    ),
    brief: t(
      'Viel Eigenleistung ist möglich, deshalb darf das Haus renovierungsbedürftig sein. Wichtig sind Grundstück und solide Substanz.',
      'Much of the work can be done themselves, so the house may need renovation. What matters is the plot and a sound structure.',
    ),
    wishes: [
      t('Grundstück ab 400 m²', 'Plot of 400 m² or more'),
      t('Garage oder Werkstatt', 'Garage or workshop'),
      t('Sanierungsbedarf kein Hindernis', 'Renovation needs are fine'),
    ],
  },
  {
    id: 'nue-07',
    city: 'nuernberg',
    districts: [
      d('erlenstegen', 'Erlenstegen'),
      d('zerzabelshof', 'Zerzabelshof'),
      d('buchenbuehl', 'Buchenbühl'),
    ],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 1_600_000,
    roomsMin: 6,
    areaMin: 200,
    financing: 'checked',
    headline: t(
      'Arztfamilie sucht Stadtvilla in gewachsener Lage',
      'Doctor’s family looking for a villa in an established area',
    ),
    brief: t(
      'Rückkehr nach Nürnberg nach mehreren Jahren im Ausland. Gesucht ist ein großzügiges Haus mit Garten und ruhigem Arbeitszimmer.',
      'Returning to Nuremberg after several years abroad. They want a spacious house with a garden and a quiet study.',
    ),
    wishes: [
      t('ruhige Seitenstraße', 'Quiet side street'),
      t('Gymnasium in der Nähe', 'Secondary school nearby'),
      t('Kauf auch vor Vermarktungsstart', 'Ready to buy before public marketing'),
    ],
  },
  {
    id: 'nue-08',
    city: 'nuernberg',
    districts: [
      d('almoshof', 'Almoshof'),
      d('kraftshof', 'Kraftshof'),
      d('neunhof', 'Neunhof'),
      d('wetzendorf', 'Wetzendorf'),
    ],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 740_000,
    roomsMin: 5,
    areaMin: 130,
    financing: 'checked',
    headline: t(
      'Familie sucht Haus im Knoblauchsland',
      'Family looking for a house in the Knoblauchsland',
    ),
    brief: t(
      'Ruhig, dörflich und trotzdem schnell in der Stadt: Gesucht ist ein Haus mit Garten im Nürnberger Norden, gern mit Platz für Tiere.',
      'Quiet and village-like, yet close to the city: they want a house with a garden in northern Nuremberg, ideally with room for pets.',
    ),
    wishes: [
      t('Garten', 'Garden'),
      t('Kita oder Grundschule im Ort', 'Nursery or primary school nearby'),
      t('Stellplatz für zwei Autos', 'Parking for two cars'),
    ],
  },
  {
    id: 'nue-09',
    city: 'nuernberg',
    districts: [
      d('buch', 'Buch'),
      d('boxdorf', 'Boxdorf'),
      d('grossgruendlach', 'Großgründlach'),
      d('schniegling', 'Schniegling'),
    ],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 690_000,
    roomsMin: 5,
    areaMin: 125,
    financing: 'checked',
    headline: t(
      'Familie sucht Doppelhaushälfte im Nürnberger Nordwesten',
      'Family looking for a semi-detached house in north-west Nuremberg',
    ),
    brief: t(
      'Drei Kinder, ein Hund, viel Alltag. Gesucht ist eine Doppelhaushälfte oder ein Reihenendhaus mit Garten und kurzen Wegen zur Schule.',
      'Three children, a dog, and a busy routine. They want a semi-detached or end-terrace house with a garden and short routes to school.',
    ),
    wishes: [
      t('Garten', 'Garden'),
      t('Schule mit dem Rad erreichbar', 'School within cycling distance'),
      t('Keller oder Hobbyraum', 'Cellar or hobby room'),
    ],
  },
  {
    id: 'nue-10',
    city: 'nuernberg',
    districts: [d('thon', 'Thon'), d('ziegelstein', 'Ziegelstein')],
    segment: 'couple',
    propertyType: 'apartment',
    budgetMax: 360_000,
    roomsMin: 3,
    areaMin: 75,
    financing: 'checked',
    headline: t(
      'Paar sucht Dreizimmerwohnung mit guter Anbindung',
      'Couple looking for a three-room apartment with good transport links',
    ),
    brief: t(
      'Eine Person pendelt zum Flughafen, die andere in die Innenstadt. Die Wohnung soll beide Wege kurz halten und Platz für ein Arbeitszimmer bieten.',
      'One commutes to the airport, the other to the city centre. The apartment should keep both commutes short and have room for a study.',
    ),
    wishes: [
      t('U-Bahn oder Straßenbahn in Laufweite', 'Underground or tram within walking distance'),
      t('Balkon', 'Balcony'),
      t('Arbeitszimmer', 'Room for a study'),
    ],
  },
  {
    id: 'nue-11',
    city: 'nuernberg',
    districts: [d('eberhardshof', 'Eberhardshof'), d('leyh', 'Leyh'), d('sandreuth', 'Sandreuth')],
    segment: 'investor',
    propertyType: 'apartment',
    budgetMax: 220_000,
    roomsMin: 2,
    areaMin: 55,
    financing: 'equity',
    headline: t(
      'Kapitalanleger sucht vermietete Zweizimmerwohnung',
      'Investor looking for a tenanted two-room apartment',
    ),
    brief: t(
      'Zweite Anlagewohnung im Nürnberger Westen. Solide Mieter und eine gepflegte Gemeinschaft sind wichtiger als eine Top-Lage.',
      'A second investment apartment in western Nuremberg. Reliable tenants and a well-run building matter more than a prime location.',
    ),
    wishes: [
      t('vermietet', 'Tenanted'),
      t('Protokolle der Eigentümerversammlungen', 'Owners’ meeting minutes'),
      t('U-Bahn-Nähe', 'Near the underground'),
    ],
  },
  {
    id: 'nue-12',
    city: 'nuernberg',
    districts: [
      d('baerenschanze', 'Bärenschanze'),
      d('suendersbuehl', 'Sündersbühl'),
      d('steinbuehl', 'Steinbühl'),
    ],
    segment: 'single',
    propertyType: 'apartment',
    budgetMax: 180_000,
    roomsMin: 1,
    areaMin: 40,
    financing: 'checked',
    headline: t(
      'Single sucht erste eigene Wohnung im Westen',
      'Single buyer looking for a first home in the west',
    ),
    brief: t(
      'Berufseinsteiger mit festem Job sucht eine kleine Wohnung zum Selbstbewohnen. Renovierungsbedarf ist in Ordnung, der Grundriss muss stimmen.',
      'A young professional in a permanent job wants a small apartment to live in. Some renovation is fine as long as the layout works.',
    ),
    wishes: [
      t('gute ÖPNV-Anbindung', 'Good public transport'),
      t('Kellerabteil', 'Storage cellar'),
      t('bezugsfrei oder bald frei', 'Vacant now or soon'),
    ],
  },
  {
    id: 'nue-13',
    city: 'nuernberg',
    districts: [
      d('gebersdorf', 'Gebersdorf'),
      d('roethenbach', 'Röthenbach'),
      d('hoefen', 'Höfen'),
    ],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 620_000,
    roomsMin: 5,
    areaMin: 125,
    financing: 'checked',
    headline: t(
      'Familie sucht Reihenhaus mit Garten im Nürnberger Westen',
      'Family looking for a terraced house with a garden in western Nuremberg',
    ),
    brief: t(
      'Die Familie wohnt schon zur Miete im Stadtteil und möchte bleiben – Freunde, Schule und Sportverein sollen in der Nähe bleiben.',
      'The family already rents in the area and wants to stay close to friends, school, and the sports club.',
    ),
    wishes: [
      t('Garten', 'Garden'),
      t('Garage', 'Garage'),
      t('Einzug zum Schuljahr 2027', 'Move-in for the 2027 school year'),
    ],
  },
  {
    id: 'nue-14',
    city: 'nuernberg',
    districts: [
      d('st-sebald', 'St. Sebald'),
      d('marienvorstadt', 'Marienvorstadt'),
      d('tafelhof', 'Tafelhof'),
    ],
    segment: 'investor',
    propertyType: 'multi-family',
    budgetMax: 2_800_000,
    financing: 'equity',
    headline: t(
      'Stiftung sucht Wohn- und Geschäftshaus in der Innenstadt',
      'Foundation looking for a mixed-use building in the city centre',
    ),
    brief: t(
      'Langfristige Anlage ohne Verkaufsabsicht. Ladenflächen im Erdgeschoss und Instandhaltungsstau sind kein Hindernis, die Substanz muss stimmen.',
      'A long-term holding with no intention to sell. Ground-floor shops and deferred maintenance are no obstacle, provided the structure is sound.',
    ),
    wishes: [
      t('ab 8 Einheiten', '8 or more units'),
      t('Denkmalschutz möglich', 'Listed building acceptable'),
      t('diskrete Abwicklung', 'Discreet transaction'),
    ],
  },
  {
    id: 'nue-15',
    city: 'nuernberg',
    districts: [
      d('rennweg', 'Rennweg'),
      d('schoppershof', 'Schoppershof'),
      d('veilhof', 'Veilhof'),
    ],
    segment: 'couple',
    propertyType: 'apartment',
    budgetMax: 390_000,
    roomsMin: 3,
    areaMin: 80,
    financing: 'checked',
    headline: t(
      'Paar sucht Wohnung mit Balkon im Nürnberger Nordosten',
      'Couple looking for an apartment with a balcony in north-east Nuremberg',
    ),
    brief: t(
      'Nach Jahren zur Miete soll es die eigene Wohnung sein. Wichtig sind Licht, ein Balkon und der Wöhrder See in Reichweite.',
      'After years of renting they want a home of their own. Light, a balcony, and the Wöhrder See within reach matter most.',
    ),
    wishes: [
      t('Balkon', 'Balcony'),
      t('ab 1. Obergeschoss', 'First floor or higher'),
      t('Stellplatz', 'Parking space'),
    ],
  },
  {
    id: 'nue-16',
    city: 'nuernberg',
    districts: [
      d('schafhof', 'Schafhof'),
      d('tullnau', 'Tullnau'),
      d('dutzendteich', 'Dutzendteich'),
    ],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 780_000,
    roomsMin: 5,
    areaMin: 130,
    financing: 'checked',
    headline: t(
      'Familie sucht Stadthaus mit kleinem Garten',
      'Family looking for a townhouse with a small garden',
    ),
    brief: t(
      'Beide arbeiten in der Stadt und möchten auf das Auto verzichten. Gesucht ist ein Haus mit kurzen Wegen zu Straßenbahn, Schule und Park.',
      'Both work in the city and want to live without a car. They want a house with short routes to the tram, school, and a park.',
    ),
    wishes: [
      t('Garten oder Terrasse', 'Garden or terrace'),
      t('Straßenbahn in Laufweite', 'Tram within walking distance'),
      t('Fahrradabstellraum', 'Bike storage'),
    ],
  },
  {
    id: 'nue-17',
    city: 'nuernberg',
    districts: [
      d('gleisshammer', 'Gleißhammer'),
      d('st-peter', 'St. Peter'),
      d('hasenbuck', 'Hasenbuck'),
    ],
    segment: 'single',
    propertyType: 'apartment',
    budgetMax: 260_000,
    roomsMin: 2,
    areaMin: 55,
    financing: 'checked',
    headline: t(
      'Single sucht Zweizimmerwohnung mit Balkon',
      'Single buyer looking for a two-room apartment with a balcony',
    ),
    brief: t(
      'Nach dem Studium in Nürnberg geblieben und jetzt bereit für Eigentum. Die Wohnung darf älter sein, sollte aber einen Balkon und eine gute Anbindung haben.',
      'Stayed in Nuremberg after university and is now ready to buy. The apartment can be older but should have a balcony and good transport links.',
    ),
    wishes: [
      t('Balkon', 'Balcony'),
      t('Straßenbahn oder S-Bahn in der Nähe', 'Tram or S-Bahn nearby'),
      t('Einbauküche', 'Fitted kitchen'),
    ],
  },
  {
    id: 'nue-18',
    city: 'nuernberg',
    districts: [d('kornburg', 'Kornburg'), d('worzeldorf', 'Worzeldorf'), d('maiach', 'Maiach')],
    segment: 'family',
    propertyType: 'house',
    budgetMax: 600_000,
    roomsMin: 5,
    areaMin: 120,
    financing: 'checked',
    headline: t(
      'Familie sucht Einfamilienhaus im Nürnberger Süden',
      'Family looking for a detached house in southern Nuremberg',
    ),
    brief: t(
      'Gesucht ist ein Haus mit Garten am grünen Stadtrand, gern in Waldnähe. Das Baujahr ist zweitrangig, der Garten nicht.',
      'They want a house with a garden on the green edge of the city, ideally near the woods. The year of construction matters less than the garden.',
    ),
    wishes: [
      t('Garten ab 300 m²', 'Garden of 300 m² or more'),
      t('Waldnähe', 'Close to the woods'),
      t('Busanbindung zur U-Bahn', 'Bus link to the underground'),
    ],
  },
  {
    id: 'nue-19',
    city: 'nuernberg',
    districts: [d('altenfurt', 'Altenfurt'), d('zollhaus', 'Zollhaus')],
    segment: 'family',
    propertyType: 'apartment',
    budgetMax: 300_000,
    roomsMin: 3,
    areaMin: 75,
    financing: 'checked',
    headline: t(
      'Alleinerziehend mit Kind sucht Dreizimmerwohnung',
      'Single parent looking for a three-room apartment',
    ),
    brief: t(
      'Gesucht ist eine Wohnung mit eigenem Kinderzimmer und kurzen Wegen zu Schule und Einkauf – am liebsten ohne Auto.',
      'They want an apartment with a separate child’s room and short routes to school and shops – ideally without needing a car.',
    ),
    wishes: [
      t('eigenes Kinderzimmer', 'A separate child’s room'),
      t('Grundschule fußläufig', 'Primary school within walking distance'),
      t('Spielplatz in der Nähe', 'Playground nearby'),
    ],
  },
  {
    id: 'nue-20',
    city: 'nuernberg',
    districts: [
      d('gartenstadt', 'Gartenstadt'),
      d('werderau', 'Werderau'),
      d('kettlersiedlung', 'Kettlersiedlung'),
    ],
    segment: 'couple',
    propertyType: 'house',
    budgetMax: 480_000,
    roomsMin: 4,
    areaMin: 100,
    financing: 'checked',
    headline: t('Paar sucht Siedlungshaus mit Garten', 'Couple looking for a garden-city house'),
    brief: t(
      'Die beiden mögen gewachsene Siedlungen mit Charakter. Ein älteres Haus mit Modernisierungsbedarf ist willkommen, der Garten ist Pflicht.',
      'They like established settlements with character. An older house needing modernisation is welcome; a garden is essential.',
    ),
    wishes: [
      t('Garten', 'Garden'),
      t('Modernisierungsbedarf in Ordnung', 'Modernisation needs are fine'),
      t('Denkmalschutz möglich', 'Listed status acceptable'),
    ],
  },
]
